[project]
authors = ["Claudius Haag <claudius.haag@mib.uni-stuttgart.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hdf5-graph"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
