# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    # inputs:
    #   message:
    #     description: "A message, displayed on the runner"

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: build and test

    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pixi install
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.26.1
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          log-level: vvv
          post-cleanup: true
          pixi-bin-path: ${{ runner.temp }}/bin/pixi
          manifest-path: pyproject.toml
      - name: Pytest
        run: pixi run test
      - name: linting with ruff
        run: pixi run lint_gh
        continue-on-error: true
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          # pytest-coverage-path: ./coverage/pytest-coverage.txt
          pytest-xml-coverage-path: ./coverage/coverage.xml
          junitxml-path: ./coverage/junit/test-results.xml
        if: github.event_name == 'pull_request'
